// Each #kernel tells which function to compile; you can have many kernels
#pragma kernel CSMain
#pragma kernel ResetMask
#include "MaskAndColourLib.hlsl"
// Create a RenderTexture with enableRandomWrite flag and set it
// with cs.SetTexture
RWStructuredBuffer<uint> _OccupancyMap, _CollisionMap;
RWTexture2D<float4> _Pixels;
float2 _cellSize;
uint _pixelsPerUnitX, _pixelsPerUnitY;
uint _GridWidth, _GridHeight;

//Share _Mask and let each projection shader add to it and then do a final pass to convert it to colour

[numthreads(8,8,1)]
void CSMain (uint3 id : SV_DispatchThreadID)
{
    int index = 
        int(id.x / _pixelsPerUnitX)+(id.y / _pixelsPerUnitY)*_GridWidth;
    if (index < 0 || index > _GridWidth * _GridHeight)
    {
        _Pixels[id.xy] = float4(1, 0, 0, 1);
        return;
    }
    else if(_CollisionMap[index] != 0)
        _Pixels[id.xy] = float4(0, 1, 0, 1);
    else if (_OccupancyMap[index] != 0)
        _Pixels[id.xy] = GetPixelColour(_OccupancyMap[index]);
    else 
        _Pixels[id.xy] = float4(0, 0, 0, 0);
}
[numthreads(64, 1, 1)]
void ResetMask (uint3 id : SV_DispatchThreadID)
{
    _OccupancyMap[id.x] = 0;
    _CollisionMap[id.x] = 0;
}
